### ISSUE TITLE
Make Darcula work on Netbeans under JDK 9.

### ISSUE THREAD

**Issue by twolf2919** [Revivius/nb-darcula#137]
The Darcula plugin causes a ClassNotFoundException when Netbeans is running on an EA version of JDK 9.  It appears to be making use of class sun.swing.SwingLazyValue which I think is no longer part of the JDK.

Strictly speaking, this is not a bug report - JDK 9 isn't even out yet, but I figure I'll make the request because JDK 9 will be out fairly soon.

**Comment by markiewb** [comment]
See PR https://github.com/Revivius/nb-darcula/pull/136

Den 28 mars 2017 15:31 skrev "twolf2919" <notifications@github.com>:

**Comment by Rahul-khandelwal** [comment]
@Revivius @markiewb , Can we have a release of nb-darcula plugin with this fix. Many people including me are using netbeans with jdk-9 EA builds and whenever we start NB, we see this exception and it is also affecting other UI components like project's subtree and code completion suggestions. Thanks.

**Comment by markiewb** [comment]
I am not the owner/maintainer of this plugin.

We could fork the plugin, apply the PR and other pending PRs and publish
it. But this won't be me! Anyone who wants to step in?

Den 31 mars 2017 06:57 skrev "Rahul-khandelwal" <notifications@github.com>:

**Comment by Rahul-khandelwal** [comment]
@markiewb @Revivius , In that case I can fork the plugin and apply the pending PRs if that is Okay. Once that is done, I can publish the plugin on github itself.

**Comment by Revivius** [comment]
@Rahul-khandelwal, @markiewb; I didnt have time for the plugin for a while. I hope to merge this PR and fix some other bugs (eg background color in Debugging Window) in a week or so.

Geertjan mentioned this in his blog too and I sure would like to use NB and Darcula on JDK9.

![debugger_sides](https://cloud.githubusercontent.com/assets/7155989/24538255/c23b253e-15f0-11e7-94f1-ac79e01eaf2e.png)

**Comment by Rahul-khandelwal** [comment]
@Revivius , If that is the case then we'll wait for next release of nb-darcula. Hope it comes soon. Thanks.

**Comment by GeertjanWielenga** [comment]
Yes, would be great to have this integrated! :-) Fantastic plugin, except for this problem.

**Comment by julioa** [comment]
Hi all,

My name is Julio and I also like this great plugin (thanks to all contributors).

It's been a while since there is a PR to fix this problem so I've decided to manually apply latest changes from pending PR along with some small updates to make it work with nightly version of netbeans and jdk9.

It works for me so if you want to use it until new version of the plugin is out you can download and see my changes at:

https://github.com/julioa/nb-darcula/releases/tag/jdk9

Hope it helps,
Julio.

**Comment by GeertjanWielenga** [comment]
Thanks!
Gj 

    On Wednesday, July 19, 2017 9:33 PM, julioa <notifications@github.com> wrote:
 

 Hi all,My name is Julio and I also like this great plugin (thanks to all contributors).It's been a while since there is a PR to fix this problem so I've decided to manually apply latest changes from pending PR along with some small updates to make it work with nightly version of netbeans and jdk9.It works for me so if you want to use it until new version of the plugin is out you can download and see my changes at:https://github.com/julioa/nb-darcula/releases/tag/jdk9Hope it helps,
Julio.—

**Comment by Revivius** [comment]
Done in 09f3a4eabd6f664e6ab1d18f2bbc665336ec02ab. Will be available in v1.6. Thank you to everyone involved.
