### ISSUE TITLE
What about to Donate the SourceCode to Apache NetBeans

### ISSUE THREAD

**Issue by lkishalmi** [Revivius/nb-darcula#161]
Dear Revivius,

This plugin is really popular among NetBeans users as it might be one of the best platform LaF available for NetBeans, and surely the best of the dark themes, though with Apache migration we've lost our Dark Metal and Dark Nimbus LaF. 

As I see no real activity on this project since almost 1.5 years, I'd like to ask, wuld it be possible to donate the source code of your plugin to Apache NetBeans, so it can be an integral part of our delivery and other people could help improving it?

**Comment by Chris2011** [comment]
That would be awesome :)

**Comment by gilbertoca** [comment]
@lkishalmi @geertjanw another plugin very popular and with problems as well is the "Display readme files in project view"  [1][2]

[1]https://github.com/markiewb/readmeinprojectview 
[2]http://plugins.netbeans.org/plugin/50171/

**Comment by Chris2011** [comment]
@gilbertoca so please make a ticket there. Your request has nothing todo with this plugin.

**Comment by yusufbaspinar** [comment]
Dear Revivius,
Thank you for your contribution to NetBeans comunity.

**Comment by Chris2011** [comment]
@lkishalmi Is it correct, that you had a talk with @Revivius in private about that? Anything new here?

**Comment by lkishalmi** [comment]
Well, he says that he would like to donate but has a busy time in his life right now.
I've prepared the integration into NB build/module system as of https://github.com/lkishalmi/incubator-netbeans/tree/nb-darcula he cloned that. All he needs to do is become an ASF Committer then file a PR.

**Comment by Chris2011** [comment]
Ahh ok, thx for the info :)

**Comment by zimmi** [comment]
Hi, I hope you are doing well!
Are there any news regarding the donation?
Darcula is my favorite theme and it would be great if it could be made an "official" part of NetBeans.
I'd also like to thank @Revivius for developing it. It must have saved a significant amount of cumulative eyesight over the years.

**Comment by lkishalmi** [comment]
Well @Revivius Is quite busy these days. Actually that's what he is telling. Fortunately/unfortunately some of his code depends on the NB Dark LaF modules, which are not donated yet (they missed the first donation train). As that issue has been resolved it is legally not possible to release the code under Apache license. 
We might ask @geertjanw that is it possible to change the schedule on that donation.

**Comment by GeertjanWielenga** [comment]
Sorry, I think this is the first I hear of this. Which undonated code exactly?

**Comment by lkishalmi** [comment]
@GeertjanWielenga Yes this is the first time I spoke of that, I was keeping that "secret" in the back of my mind.
Things like this: https://github.com/lkishalmi/netbeans/blob/nb-darcula/platform/c.revivius.nb.darcula/src/com/revivius/nb/darcula/DarkIconFilter.java
Probably there is one or two more.
And the undonated code would be the dark LaF-s (dark Metal and Nimbus) which is scheduled for the V. donation according to: https://cwiki.apache.org/confluence/display/NETBEANS/Apache+Transition

**Comment by geertjanw** [comment]
Where in this repo are the files found, which specific files in this repo are we talking about: https://hg.netbeans.org/releases/file

**Comment by geertjanw** [comment]
Ah, OK, I see, this: https://hg.netbeans.org/core-main/file/tip/o.n.swing.laf.dark

**Comment by lkishalmi** [comment]
Yes, that one!

**Comment by geertjanw** [comment]
OK, looks like it will still take quite some time, the 4th donation scheduled for around September, but am trying to see if we can squeeze this in too.

**Comment by Chris2011** [comment]
I really like darcula and I use it every day, but it still has some UI downsides. It is a mix of some old NetBeans stuff like gradients and flat and clean design. IMHO we should focus on flatlaf: https://github.com/JFormDesigner/FlatLaf it still has HiDPI support, looks flat (no shadows, no gradients, this is what flat means) and it comes from the JFormDesigner developers, so I guess there are more people involved in that, than here. The license is already Apache 2.0.

Here you can see a very first quick experiment by adding it into my plugin:

![image](https://user-images.githubusercontent.com/795658/68481386-57570900-0237-11ea-9e17-62b07f495073.png)

It looks very nice and clean, but still has some problems. But I think this is the way to go instead of using this code here.

Here is the comparison between the FlatDarculaLaf (left) and the nb-darcula (right):

![image](https://user-images.githubusercontent.com/795658/68481791-67231d00-0238-11ea-9b10-a99518ef3c7f.png)


It has these look and feels:

* Flat Light
(class com.formdev.flatlaf.FlatLightLaf)
* Flat Dark
(class com.formdev.flatlaf.FlatDarkLaf)
* Flat IntelliJ
(class com.formdev.flatlaf.FlatIntelliJLaf)
looks like IntelliJ theme from IntelliJ IDEA 2019.2+
* Flat Darcula
(class com.formdev.flatlaf.FlatDarculaLaf)
looks like Darcula theme from IntelliJ IDEA 2019.2+

Here is the site of the project: https://www.formdev.com/flatlaf/

**Comment by lkishalmi** [comment]
FlatLaf won. It will be released in NetBeans 11.3
