### ISSUE TITLE
Replace dotted header icons

### ISSUE THREAD

**Issue by markiewb** [Revivius/nb-darcula#34]
![2016-01-25_21h03_24](https://cloud.githubusercontent.com/assets/1857095/12562756/1d4ec770-c3a7-11e5-88e2-6033c5b06015.png)

See also the latest screenshots from @ZMichaelChow at https://github.com/Revivius/nb-darcula/issues/20
He compared several other LAFs and also the Darcula LAF from IDEA

**Comment by Revivius** [comment]
@markiewb, @ZMichaelChow let me try.

**Comment by markiewb** [comment]
That would be cool! Thanks!

**Comment by Revivius** [comment]
Well; after some digging in NetBeans sources I can see that a hardcoded colors is used:

```java
package org.netbeans.swing.tabcontrol.plaf;

abstract class AbstractWinViewTabDisplayerUI {
    @Override
    protected void paintTabContent(Graphics g, int index, String text, int x,
                                   int y, int width, int height) {
        ...
        if( isUseStretchingTabs() ) {
            ColorUtil.paintVistaTabDragTexture(getDisplayer(), g, x + BUMP_X_PAD, y
                     + BUMP_Y_PAD_UPPER, height - (BUMP_Y_PAD_UPPER
                     + BUMP_Y_PAD_BOTTOM));
        }
        ...
    }
}

final class ColorUtil {
    ...
    /**
     * Draws drag texture of the tab in specified bounds.
     */
    public static void paintVistaTabDragTexture(Component control, Graphics g,
                                             int x, int y, int height) {
        if (VISTA_DRAG_IMAGE == null) {
            VISTA_DRAG_IMAGE = initVistaDragTextureImage();
        }
        int count = height / 4;
        int ypos = y;
606:    g.setColor( Color.WHITE ); // <<<<<--- How to hack this ?
        for (int i = 0; i < count; i++) {
            VISTA_DRAG_IMAGE.paintIcon(control, g, x, ypos);
            g.drawLine( x+1, ypos+2, x+2, ypos+2 );
            g.drawLine( x+2, ypos+1, x+2, ypos+1 );
            ypos += 4;
        }
    }
    ...
}
```

So if we keep using stretched tabs I dont see a way of changing the hardcoded white color in ColorUtil:606. But If we drop using stretched tabs (which is default since NB 8.0 I think) dotted icon not painted:

![non_stretched_tabs](https://cloud.githubusercontent.com/assets/7155989/12595626/0de1b822-c485-11e5-9521-027a55051186.png)

 **Personally I think stretched tabs are better and current icon is not that bad. What say you ?**

**Comment by markiewb** [comment]
IMO the non-streched variant looks OK for me. 

Provide an option and let the user decide. It would be a waste of your invested free-time, if there is no output.

**Comment by Saljack** [comment]
Non-streched variant is better for me because there are not minimaze button on tab. I have problem with order of close, minimaze buttons. I think order minimaze before close makes more sense
![minimazebutton](https://cloud.githubusercontent.com/assets/614424/12606282/67f7f37a-c4cc-11e5-8ee0-fe4ad7b96633.PNG)
.

**Comment by ZMichaelChow** [comment]
Non-streched tabs is better for me, too. I always make the tabs non-streched :)
I agree with **@markiewb**. If possible(and convenient), provide an option in "Tools->Options" and let the user decide.

**Comment by Revivius** [comment]
OK! now user can opt to use stretched tabs or not. Tabs are not stretched by default:

![stretched_tabs](https://cloud.githubusercontent.com/assets/7155989/12625923/9bbaff64-c53e-11e5-965f-2a7682f14293.png)

Thanks everybody for opinions.

**Comment by markiewb** [comment]
Thank you too!

**Comment by ZMichaelChow** [comment]
Well done! Thank you so much~
