### ISSUE TITLE
Replace icon for JOptionPane with nicer icons

### ISSUE THREAD

**Issue by markiewb** [Revivius/nb-darcula#46]
![2016-01-27_21h55_16](https://cloud.githubusercontent.com/assets/1857095/12628148/115b49f6-c542-11e5-8e75-d87f17a2b330.png)

I haven't seen such icons in Idea yet, so I cannot provide you an expected state. 
Keep this issue for the record

**Comment by granella** [comment]
Github was unstable in this early hours :)
closed PR for my branch and adding correct PR

**Comment by AlexFalappa** [comment]
@granella: do you think to open a PR for improving the JOptionPane icons also against the original [Darcula project](https://github.com/bulenkov/Darcula)?

I would be interested in that. It seems to me that the original project is stalling, I would be in favour maintaining an improved fork of the LAF alone where contributions like yours could be integrated.

Since a lot of improvements seem to come from this project why not let @Revivius create it?

**Comment by Revivius** [comment]
@AlexFalappa modifications and fixes we are performing takes effect **only when it is loaded by NetBeans Platform**. For example, try placing a JToggleButton in Form Designer and notice that how different it is from the 'Source' button in editor multiview. Form Designer is using *unmodified Darcula LAF* and hence has different borders for buttons for instance. Long story short, I think contributing to or forking original LAF should be the route we take eventually.

**Comment by Revivius** [comment]
Fixed with merging of PR #50. Thank you @granella !

**Comment by AlexFalappa** [comment]
@Revivius I played a bit with the _Darcula LAF_ using it in some test Swing apps and found some lacks indeed.

An evident lack is missing JToggleButton styling as you highlighted. Other lacks I found are bad JOptionPane icons, less than optimal TitledBorder appearance, no JButton prelighting on mouse hover and no pressed state, no styling of JSplitPane (there is a pull request for this in the Darcula project however).

I plan on tackling the JToggleButton support, I'll keep you informed
