### ISSUE TITLE
Tabs revert back to standard color after a few seconds

### ISSUE THREAD

**Issue by epochcoder** [Revivius/nb-darcula#83]
Everything else seems to be correct, but the open file tabs within the editor seem to switch back to the windows style after a few seconds of starting up.

please let me know if I can supply any logs, additional information

[Screenshot](http://i.imgur.com/7Yz8Jyy.png)

**Comment by Revivius** [comment]
@epochcoder; are you using "same background color for files from same project" feature ?
![color_files](https://cloud.githubusercontent.com/assets/7155989/13740414/5d415f48-e9d9-11e5-948c-bfd33a8083fd.png)


I think what you see is not due to change of tab styles but due to colors and is expected result.

Still; we should replace the 'close' icon there.

**Comment by epochcoder** [comment]
@Revivius, thank you! that was the issue :)

Great work on the project btw; I'll close the ticket :)
