### ISSUE TITLE
No versioning color in tabs and Projects

### ISSUE THREAD

**Issue by Saljack** [Revivius/nb-darcula#9]
I haven't tab name with versioning color. Name is white. It is broken in Projects (Files, Favorites) panel too. 
![versioncolordracula](https://cloud.githubusercontent.com/assets/614424/12475768/64483baa-c025-11e5-9e70-0902d280713d.PNG)
![versioncolor](https://cloud.githubusercontent.com/assets/614424/12475769/644943ec-c025-11e5-8375-a098c4698dc5.PNG)

**Comment by granella** [comment]
Hi, I'm modifying the plugin to include the imitation of default Darcula theme ( https://github.com/granella/Netbeans-Darcula-Theme). Also included will be the colors of version control.

Soon I will send a pull request.

Look:
![screenshot from 2016-01-21 07 56 21](https://cloud.githubusercontent.com/assets/859038/12477174/3df2165c-c015-11e5-8dc8-32c25f6d7fb2.png)

**Comment by Saljack** [comment]
Thank you very much

**Comment by Revivius** [comment]
@Saljack, those colors are theme related. On NB 8.1 there is a warning (it was not there for NB 8.0). Here:
![version_colors](https://cloud.githubusercontent.com/assets/7155989/12478488/d9069abe-c03d-11e5-8619-7d9e68d667b1.png)

@granella I like your theme a lot, thank you! I was wondering how to include a theme with the plugin, I would be very happy to merge your pull request. But I have a small wishlist if possible:
  1. Can we please use Monospaced font instead of Source Code Pro (both in editor and output) as you described in your theme ? 
  2. There are some black colors (eg Java>Javadoc Identifier) and some highlights (eg breakpoints) are not readable. Would you mind changing those too ?

Thanks.

**Comment by Saljack** [comment]
I use NB 8.1. Colors are ok if I use Multi-row tab options. But my main problem is no versioning colors in Projects, Files and Favorites panel.

**Comment by granella** [comment]
@Revivius I would be happy if you merge my pull request.
and about:
1. yeah!
2. yeah, thanks!

@Saljack Project/Files browser need another attention too :(

**Comment by javydreamercsw** [comment]
That would be awesome, thanks!

**Comment by Revivius** [comment]
@Saljack which color theme are you using ?

**Comment by Revivius** [comment]
@Saljack, this is fixed with the modifications based on the PR #19 thanks to @granella:

![versioning](https://cloud.githubusercontent.com/assets/7155989/12536758/89cc65d8-c2b7-11e5-9c04-8f0320cdac66.png)

**Comment by javydreamercsw** [comment]
Awesome!

**Comment by Saljack** [comment]
I found solution how to fix this issues I need click on every items in Font & Colors -> Versioning -> Subversion -> Highlighting on Reset colors button. It starts working after then. Thanks for help
