### ISSUE TITLE
Print wrong from Netbeans

### ISSUE THREAD

**Issue by aleksano** [Revivius/nb-darcula#92]
Menu File-Print-Parameters Print
1) Don't work with Print As Editor = false - empty preview
2) Don't work line wrapping
Thanks

**Comment by Revivius** [comment]
@aleksano; If you select "Print as in Editor" the options font, color and layout including "Wrap Lines" become disabled. Since I think you are telling NetBeans to print it with exact font, colors and layout in the editor.

If you dont select  "Print as in Editor" (set it to false) "Wrap Lines" work as expected:

![printpreview](https://cloud.githubusercontent.com/assets/7155989/14440128/3aac919a-0037-11e6-9298-f71832b42934.png)

Can you explain the problem please ?

**Comment by aleksano** [comment]
Thanks/ That's all right.
